version: '3.8'
services:
  my-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: my-server
    working_dir: /proj
    volumes:
      - ./src:/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - my-database
      - my-redis
  my-database:
    image: mysql:8.0.32
    container_name: my-database
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  my-redis:
    image: redis:7
    container_name: my-redis
    ports:
      - ${REDIS_PORT}:6379
    extra_hosts:
      - 'host.docker.internal:host-gateway'
