name: Deploy to EC2
on:
  push:
    branches:
      - develop
env:
  ELASTIC_IP: ${{ secrets.ELASTIC_IP }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DEV_EC2_PRIVATE_IP: ${{ secrets.DEV_EC2_PRIVATE_IP }}
  DEV_BASTION_PUBLIC_IP: ${{ secrets.DEV_BASTION_IP }}
  DEV_ENV_CONTENT: ${{ vars.DEV_ENV_CONTENT }}
  DEV_APPLICATION_PATH: ${{ vars.DEV_APPLICATION_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy .env.dev to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          proxy_host: ${{ secrets.DEV_BASTION_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}
          proxy_port: 22
          script: |
            cd ${{ env.DEV_APPLICATION_PATH }}
            mkdir -p ./config
            echo "${{ env.DEV_ENV_CONTENT }}" > ./config/.env.dev

      - name: Git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          proxy_host: ${{ secrets.DEV_BASTION_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}
          proxy_port: 22
          script: |
            cd ${{ env.DEV_APPLICATION_PATH }}
            if git pull origin develop; then
              echo "Git pulled successfully"
            else
              echo "Git pulled failed" && exit 1
            fi
      # - name: Restart server with docker
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ env.ELASTIC_IP }}
      #     username: ubuntu
      #     key: ${{ env.SSH_KEY }}
      #     port: 22
      #     script: |
      #       cd ${{ env.DEV_APPLICATION_PATH }}
      #       if yarn docker:dev; then
      #         echo "Server restarted successfully"
      #       else
      #         echo "Server restarted failed" && exit 1
      #       fi
      - name: Restart server with pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_PRIVATE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          debug: true
          proxy_host: ${{ secrets.DEV_BASTION_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.SSH_KEY }}
          proxy_port: 22
          script: |
            cd ${{ env.DEV_APPLICATION_PATH }}
            if /home/ubuntu/.nvm/versions/node/v20.8.1/bin/pm2 restart all; then
              echo "Server restarted successfully"
            else
              echo "Server restarted failed" && exit 1
            fi
